In [3]:
import pandas as pd

wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [4]:
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [5]:
data = wine[['alcohol', 'sugar', 'pH']]
target = wine[['class']]

In [6]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = \
train_test_split(data, target, random_state=42)

In [7]:
sub_input, val_input, sub_target, val_target =\
train_test_split(train_input, train_target, random_state=42)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [12]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target)
import numpy as np
np.mean(scores['test_score'])

np.float64(0.8569392934238931)

In [13]:
from sklearn.model_selection import StratifiedKFold

In [14]:
cross_validate(dt, train_input, train_target, cv=splitter)

NameError: name 'splitter' is not defined

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
params = {
    'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]
}

In [18]:
dt = DecisionTreeClassifier(random_state=42)
gs = GridSearchCV(dt, params)

In [19]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [20]:
gs.best_estimator_

DecisionTreeClassifier(min_impurity_decrease=0.0003, random_state=42)

In [24]:
import numpy as np
params = {
    'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
    'max_depth': range(5, 20, 1),
    'min_samples_split': range(2, 100, 10)
}

In [25]:
dt = DecisionTreeClassifier(random_state=42)

gs = GridSearchCV(dt, params, n_jobs=-1)

In [26]:
gs.fit(train_input, train_target)

/Users/june/Desktop/DMF/ML/venv/lib/python3.12/site-packages/numpy/ma/core.py:2846: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [27]:
gs.best_params_

{'max_depth': 15,
 'min_impurity_decrease': np.float64(0.0001),
 'min_samples_split': 22}

In [29]:
gs.cv_results_['mean_test_score']

array([0.85837161, 0.85837161, 0.85837161, ..., 0.86309693, 0.86309693,
       0.86309693])

In [30]:
from scipy.stats import uniform, randint

In [33]:
randint(0, 10).rvs(10)

array([3, 1, 9, 5, 7, 2, 3, 0, 6, 2])

In [41]:
rgen = randint(0, 10)
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([114, 110,  94,  91, 105,  81, 102,  89, 110, 104]))

In [42]:
params = {
    'min_impurity_decrease': uniform(0.0001, 0.001),
    'max_depth': randint(20, 50),
    'min_samples_split': randint(2, 25),
    'min_samples_leaf': randint(1, 25),
}

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
gs = RandomizedSearchCV(dt, params, n_iter=100, n_jobs=-1)

In [46]:
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x116136000>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x1161379b0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x116397830>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x116394b00>})

In [47]:
gs.best_estimator_

DecisionTreeClassifier(max_depth=27,
                       min_impurity_decrease=np.float64(0.00027229560353868445),
                       min_samples_leaf=9, min_samples_split=22,
                       random_state=42)

In [48]:
gs.best_params_

{'max_depth': 27,
 'min_impurity_decrease': np.float64(0.00027229560353868445),
 'min_samples_leaf': 9,
 'min_samples_split': 22}